name: kimu_foods
description: Kimu Foods
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  provider: ^6.1.1
  graphql_flutter: ^5.2.0-beta.6
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/core/assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: lib/core/assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib/core/assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/core/assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/core/assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: lib/core/assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/core/assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: lib/core/assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/core/assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/core/assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: lib/core/assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/core/assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/core/assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/core/assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/core/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/core/assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/core/assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: lib/core/assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
  assets:
    - lib/core/assets/svgs/
